target 'readlater' do
  use_frameworks!
  platform :ios, '16'
  pod 'common', :path => '../common'

  target 'readlaterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'readlaterUITests' do
    # Pods for testing
  end

end
