target 'readlater' do
  use_frameworks!
  platform :ios, '17'
  pod 'common', :path => '../common'

  target 'readlaterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'readlaterUITests' do
    # Pods for testing
  end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17'
        end
      end
    end

end
