target 'readlater' do
  use_frameworks!
  platform :ios, '16'
  pod 'data', :path => '../data'

  target 'readlaterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'readlaterUITests' do
    # Pods for testing
  end

end
