name: Build iOS

on:
  push:
    branches: ['master']
    paths-ignore: ['**.md', 'knapsack-android/**']

  pull_request:
    branches: ['master']
    paths-ignore: ['**.md', 'knapsack-android/**']

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app && /usr/bin/xcodebuild -version

      - name: Build common
        run: ./gradlew :common:linkPodDebugFrameworkIos

      - name: Install pods
        run: pod install
        working-directory: ./knapsack-ios

      - name: Run tests
        run: xcodebuild test -scheme readlater -workspace readlater.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.0' | xcpretty && exit ${PIPESTATUS[0]}
        working-directory: ./knapsack-ios
